# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Union Colombo Washing Plant',
    'version': '1',
    'website': 'https://www.subtletechs.com/',
    'author': 'Subtle Technologies (Pvt) Ltd',
    'depends': [
        'base',
        'stock',
        'sale',
        'mrp',
        'quality',
        'quality_control',
        'hr',
        'sale',
        'purchase',
        'mail',
    ],
    'data': [
        'report/quality_check_report.xml',
        'data/inventory_locations.xml',
        'data/receipts_data.xml',
        'data/stock_data.xml',
        'data/sequence_data.xml',
        'data/pre_costing_data.xml',
        'data/style_expire_cron.xml',
        'data/email_templates.xml',
        'security/ir.model.access.csv',
        'ucwp_stock/product_template.xml',
        'ucwp_stock/stock_move.xml',
        'ucwp_stock/ucwp_fabric_type.xml',
        'ucwp_stock/ucwp_wash_type.xml',
        'ucwp_stock/ucwp_garment_type.xml',
        'ucwp_stock/stock_move_line_barcode.xml',
        'ucwp_stock/res_config_settings.xml',
        'ucwp_stock/product_name_change_log.xml',
        'ucwp_stock/lot_creation_view.xml',
        'ucwp_stock/internal_lab_tests_view.xml',
        'ucwp_sale/sale_order.xml',
        'ucwp_sale/res_partner_view.xml',
        'ucwp_mrp/mrp_bom_views.xml',
        'ucwp_quality/quality_views.xml',
        'ucwp_quality/ucwp_defects.xml',
        'ucwp_quality/ucwp_quality_check_view.xml',
        'ucwp_mrp/mrp_production_view.xml',
        'ucwp_mrp/job_card.xml',
        'ucwp_account/ucwp_account_move_views.xml',
        'ucwp_stock/stock_picking_return_view.xml',
        'ucwp_pre_costing/ucwp_pre_costing_view.xml',
        'ucwp_pre_costing/ucwp_pre_costing_approval_view.xml',
        'ucwp_purchase/ucwp_purchase_requisition_view.xml',
        'ucwp_purchase/purchase_views.xml',
        'ucwp_purchase/res_partner_views.xml',
    ],

    'installable': True,
    'application': True,
}
