from . import product_template
from . import ucwp_fabric_type
from . import ucwp_wash_type
from . import ucwp_garment_type
from . import ucwp_garment_sample
from . import stock_move
from . import stock_picking_return
from . import res_config_settings
from . import product_name_change_log
from . import lot_creation
from . import internal_lab_tests
